MODULE MOD_READDATA
 USE  MOD_ALLOCATE
 PRIVATE
 PUBLIC :: READINPUT
 PUBLIC :: READ_GRID
 CONTAINS
 SUBROUTINE READINPUT(RUNDATA,aa)
    USE MOD_KINDS
    USE MOD_GLOBAL,ONLY :TIME,TIMEB,TIMEE,NTB,NTE,IMALL,JMALL,IMSUB,JMSUB, &
                        & DTE_ALL,DTI_ALL,ISPLIT_ALL,DTE_SUB,DTI_SUB,ISPLIT_SUB, &
                        & MODE,ICOUPLE,TIMESTEP, GRAV,TBIAS,SBIAS, ALLNAME, SUBNAME,i
    IMPLICIT NONE
    CHARACTER(LEN=100),INTENT(IN)::RUNDATA,AA
    CHARACTER(LEN=100) ::TMPSTRING
    TYPE(TIME) :: START_TIME,END_TIME,MODEL_TIME
    write(*,*) "Reading the CONTROL file....", TRIM(RUNDATA)
    if(trim(AA).eq.'ALL') then
		OPEN(11,FILE=TRIM(RUNDATA),STATUS='OLD')
        READ(11,*) TMPSTRING
		READ(11,*) START_TIME%YEAR,START_TIME%MONTH,START_TIME%DAY,START_TIME%HOUR,START_TIME%MINUTE ! THE START DATE
        READ(11,*) TMPSTRING
		READ(11,*) END_TIME%YEAR,END_TIME%MONTH,END_TIME%DAY,END_TIME%HOUR,END_TIME%MINUTE ! THE START DATE
        TIMEB=TIMEFUN(START_TIME%YEAR,START_TIME%MONTH,START_TIME%DAY,START_TIME%HOUR,START_TIME%MINUTE,0) ! IN HOURS
		TIMEE=TIMEFUN(END_TIME%YEAR,END_TIME%MONTH,END_TIME%DAY,END_TIME%HOUR,END_TIME%MINUTE,0) ! IN HOURS
	    MODEL_TIME%YEAR=START_TIME%YEAR
        MODEL_TIME%MONTH=START_TIME%MONTH
        MODEL_TIME%DAY  =START_TIME%DAY
        MODEL_TIME%HOUR=START_TIME%HOUR
        MODEL_TIME%MINUTE=START_TIME%MINUTE
        READ(11,*) TMPSTRING
        READ(11,*) ALLNAME
        READ(11,*) IMALL,JMALL
        READ(11,*) TMPSTRING
        READ(11,*) SUBNAME
        READ(11,*) IMSUB,JMSUB
		!this is all_domain value
		READ(11,*) DTE_ALL ! POM EXTERNAL MODE TIME STEP, IN SECONDS
		READ(11,*) ISPLIT_ALL ! TIMES OF INTERNAL MODE TIME STEP OVER THE EXTERNAL
		!below is global value
		READ(11,*) 	TIMESTEP  ! ENVIRONMENT, BIOCHEMICAL L TIME STEP, IN HOURS
		READ(11,*) TMPSTRING    !NO USED
		READ(11,*) TMPSTRING    !NO USED
		READ(11,*) MODE,ICOUPLE !ICOPLE=1 NEXT RUN, =0 NOT COUPLE,-1 ONLY COASE 
		READ(11,*)              !DEPTH_1D ! METER
		READ(11,*) TMPSTRING    !NO USED  ! COLD/HOT START OPTION (0/1)	
		READ(11,*) TMPSTRING	  !NO USED !TIME STEP TO BACKUP FOR RESTART
		READ(11,*) GRAV       !GEOGRAPHYCAL GRAVITY
		READ(11,*) TBIAS        ! REFERENCE TEMPERATURE
		READ(11,*) SBIAS        ! REFERENCE SALINITY
		read(11,*) 
		read(11,*) ! skip sub step
		CLOSE(11)
        DTI_ALL=DTE_ALL*ISPLIT_ALL ! POM INTERNAL MODE TIME STEP, IN SECONDS
        NTB=1
		NTE=INT(3600.*(TIMEE-TIMEB)/DTI_ALL)
        CALL MYALLOCATE_ALL
    endif

   	if(trim(aa).eq.'sub') then
		OPEN(12,FILE=TRIM(RUNDATA),STATUS='OLD')
		do i=1,20
		  read(12,*)
		enddo
		READ(12,*) DTE_SUB ! POM EXTERNAL MODE TIME STEP, IN SECONDS
		READ(12,*) ISPLIT_SUB ! TIMES OF INTERNAL MODE TIME STEP OVER THE EXTERNAL
		DTI_SUB=DTE_SUB*ISPLIT_SUB ! POM INTERNAL MODE TIME STEP, IN SECONDS
		close(12)

		if((dti_sub.ne.dti_all).or.(dte_all/dte_sub.ne.int(dte_all/dte_sub))) then
			print*, 'errord ti_sub.ne.dti_all'
			print*, 'errord dte_all/dte_sub shall be n'
			stop
		endif
        CALL MYALLOCATE_SUB
	ENDIF
        
	RETURN
	END SUBROUTINE READINPUT
    
    FUNCTION TIMEFUN(IY,IM,ID,IH,MIN,ISEC)
 	IMPLICIT NONE

	REAL TIMEFUN
	INTEGER MN(12),MN1(12),IY,IM,ID,IH,MIN,Isec,iyy,iyy1
    INTEGER IDD
	DATA MN/0,31,59,90,120,151,181,212,243,273,304,334/
	DATA MN1/0,31,60,91,121,152,182,213,244,274,305,335/
	IDD=365*(IY-1)+(IY-1)/4-(IY-1)/100+(IY-1)/400
	IYY=(IY-1)/4-(IY-1)/100+(IY-1)/400
	IYY1=IY/4-IY/100+IY/400
	IF(IYY1.GT.IYY) THEN
	  IDD=IDD+MN1(IM)+ID-1
	ELSE
	  IDD=IDD+MN(IM)+ID-1
	ENDIF
	TIMEFUN=0.24D2*IDD+.1D1*IH+MIN/0.6D2+ISEC/3600.  ! IN HOURS
!	print*,TIMEFUN,IY,IM,ID,IH,MIN
	RETURN
	END function
 END MODULE MOD_READDATA
